GET http://localhost:30000/database
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwODEyOTYiLCJuYW1lIjoibWFzdGVyIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE2Njk4MjAzNzB9.nQrtBB6suZ49uJsVGFg0w5uY0OcZn4iGubYsOsTqqYBR7xl5RSmmmgMm4Q6RM5wDup4eKmipFruc6ijSsdX6XozxoCRtrev0tuWsT1u5gL5IrkDPSeJv-jAckf1qQBGWBDftOwCbxDSvch2mRQ9CezLd1-1Rpn8DLVMxUA0soyGCAZ5mFsrSKqaqVEHq5Sp_nwrxjWoQWX9KH9TPjTpq2W2HwqZUGc48ejQO6C3h7Vx7mzZZwylN5_ckcU1eXkmIqIp0kCbU4qEUNOlPNxunA2109y_R4pZ9z3dWOYmEhYdIQ2HEnuba2Bzp6S7bQg6HYP7u8Qqe53tHR4-lZQLznw
Content-Type: application/json

###
GET http://localhost:30000/database/053f98e0-b22a-4db8-b17d-16143b970430
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwODEyOTYiLCJuYW1lIjoibWFzdGVyIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE2Njk4MjAzNzB9.nQrtBB6suZ49uJsVGFg0w5uY0OcZn4iGubYsOsTqqYBR7xl5RSmmmgMm4Q6RM5wDup4eKmipFruc6ijSsdX6XozxoCRtrev0tuWsT1u5gL5IrkDPSeJv-jAckf1qQBGWBDftOwCbxDSvch2mRQ9CezLd1-1Rpn8DLVMxUA0soyGCAZ5mFsrSKqaqVEHq5Sp_nwrxjWoQWX9KH9TPjTpq2W2HwqZUGc48ejQO6C3h7Vx7mzZZwylN5_ckcU1eXkmIqIp0kCbU4qEUNOlPNxunA2109y_R4pZ9z3dWOYmEhYdIQ2HEnuba2Bzp6S7bQg6HYP7u8Qqe53tHR4-lZQLznw
Content-Type: application/json

###
POST http://localhost:30000/database
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwODEyOTYiLCJuYW1lIjoibWFzdGVyIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE2Njk4MjAzNzB9.nQrtBB6suZ49uJsVGFg0w5uY0OcZn4iGubYsOsTqqYBR7xl5RSmmmgMm4Q6RM5wDup4eKmipFruc6ijSsdX6XozxoCRtrev0tuWsT1u5gL5IrkDPSeJv-jAckf1qQBGWBDftOwCbxDSvch2mRQ9CezLd1-1Rpn8DLVMxUA0soyGCAZ5mFsrSKqaqVEHq5Sp_nwrxjWoQWX9KH9TPjTpq2W2HwqZUGc48ejQO6C3h7Vx7mzZZwylN5_ckcU1eXkmIqIp0kCbU4qEUNOlPNxunA2109y_R4pZ9z3dWOYmEhYdIQ2HEnuba2Bzp6S7bQg6HYP7u8Qqe53tHR4-lZQLznw
Content-Type: application/json

{
  "logger": "<New Name>"
}
###
DELETE http://localhost:30000/database/<id>
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwODEyOTYiLCJuYW1lIjoibWFzdGVyIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE2Njk4MjAzNzB9.nQrtBB6suZ49uJsVGFg0w5uY0OcZn4iGubYsOsTqqYBR7xl5RSmmmgMm4Q6RM5wDup4eKmipFruc6ijSsdX6XozxoCRtrev0tuWsT1u5gL5IrkDPSeJv-jAckf1qQBGWBDftOwCbxDSvch2mRQ9CezLd1-1Rpn8DLVMxUA0soyGCAZ5mFsrSKqaqVEHq5Sp_nwrxjWoQWX9KH9TPjTpq2W2HwqZUGc48ejQO6C3h7Vx7mzZZwylN5_ckcU1eXkmIqIp0kCbU4qEUNOlPNxunA2109y_R4pZ9z3dWOYmEhYdIQ2HEnuba2Bzp6S7bQg6HYP7u8Qqe53tHR4-lZQLznw
Content-Type: application/json

###
PUT http://localhost:30000/database/<id>
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwODEyOTYiLCJuYW1lIjoibWFzdGVyIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE2Njk4MjAzNzB9.nQrtBB6suZ49uJsVGFg0w5uY0OcZn4iGubYsOsTqqYBR7xl5RSmmmgMm4Q6RM5wDup4eKmipFruc6ijSsdX6XozxoCRtrev0tuWsT1u5gL5IrkDPSeJv-jAckf1qQBGWBDftOwCbxDSvch2mRQ9CezLd1-1Rpn8DLVMxUA0soyGCAZ5mFsrSKqaqVEHq5Sp_nwrxjWoQWX9KH9TPjTpq2W2HwqZUGc48ejQO6C3h7Vx7mzZZwylN5_ckcU1eXkmIqIp0kCbU4qEUNOlPNxunA2109y_R4pZ9z3dWOYmEhYdIQ2HEnuba2Bzp6S7bQg6HYP7u8Qqe53tHR4-lZQLznw
Content-Type: application/json

{
  "logger": "<New Name>"
}
###
GET http://localhost:8080/database
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwODEyOTYiLCJuYW1lIjoibWFzdGVyIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE2Njk4MjAzNzB9.nQrtBB6suZ49uJsVGFg0w5uY0OcZn4iGubYsOsTqqYBR7xl5RSmmmgMm4Q6RM5wDup4eKmipFruc6ijSsdX6XozxoCRtrev0tuWsT1u5gL5IrkDPSeJv-jAckf1qQBGWBDftOwCbxDSvch2mRQ9CezLd1-1Rpn8DLVMxUA0soyGCAZ5mFsrSKqaqVEHq5Sp_nwrxjWoQWX9KH9TPjTpq2W2HwqZUGc48ejQO6C3h7Vx7mzZZwylN5_ckcU1eXkmIqIp0kCbU4qEUNOlPNxunA2109y_R4pZ9z3dWOYmEhYdIQ2HEnuba2Bzp6S7bQg6HYP7u8Qqe53tHR4-lZQLznw
Content-Type: application/json

###
GET http://localhost:8080/database/053f98e0-b22a-4db8-b17d-16143b970430
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwODEyOTYiLCJuYW1lIjoibWFzdGVyIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE2Njk4MjAzNzB9.nQrtBB6suZ49uJsVGFg0w5uY0OcZn4iGubYsOsTqqYBR7xl5RSmmmgMm4Q6RM5wDup4eKmipFruc6ijSsdX6XozxoCRtrev0tuWsT1u5gL5IrkDPSeJv-jAckf1qQBGWBDftOwCbxDSvch2mRQ9CezLd1-1Rpn8DLVMxUA0soyGCAZ5mFsrSKqaqVEHq5Sp_nwrxjWoQWX9KH9TPjTpq2W2HwqZUGc48ejQO6C3h7Vx7mzZZwylN5_ckcU1eXkmIqIp0kCbU4qEUNOlPNxunA2109y_R4pZ9z3dWOYmEhYdIQ2HEnuba2Bzp6S7bQg6HYP7u8Qqe53tHR4-lZQLznw
Content-Type: application/json

###
POST http://localhost:8080/database
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwODEyOTYiLCJuYW1lIjoibWFzdGVyIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE2Njk4MjAzNzB9.nQrtBB6suZ49uJsVGFg0w5uY0OcZn4iGubYsOsTqqYBR7xl5RSmmmgMm4Q6RM5wDup4eKmipFruc6ijSsdX6XozxoCRtrev0tuWsT1u5gL5IrkDPSeJv-jAckf1qQBGWBDftOwCbxDSvch2mRQ9CezLd1-1Rpn8DLVMxUA0soyGCAZ5mFsrSKqaqVEHq5Sp_nwrxjWoQWX9KH9TPjTpq2W2HwqZUGc48ejQO6C3h7Vx7mzZZwylN5_ckcU1eXkmIqIp0kCbU4qEUNOlPNxunA2109y_R4pZ9z3dWOYmEhYdIQ2HEnuba2Bzp6S7bQg6HYP7u8Qqe53tHR4-lZQLznw
Content-Type: application/json

{
  "logger": "Sandy Claws"
}
###
DELETE http://localhost:8080/database/<id>
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwODEyOTYiLCJuYW1lIjoibWFzdGVyIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE2Njk4MjAzNzB9.nQrtBB6suZ49uJsVGFg0w5uY0OcZn4iGubYsOsTqqYBR7xl5RSmmmgMm4Q6RM5wDup4eKmipFruc6ijSsdX6XozxoCRtrev0tuWsT1u5gL5IrkDPSeJv-jAckf1qQBGWBDftOwCbxDSvch2mRQ9CezLd1-1Rpn8DLVMxUA0soyGCAZ5mFsrSKqaqVEHq5Sp_nwrxjWoQWX9KH9TPjTpq2W2HwqZUGc48ejQO6C3h7Vx7mzZZwylN5_ckcU1eXkmIqIp0kCbU4qEUNOlPNxunA2109y_R4pZ9z3dWOYmEhYdIQ2HEnuba2Bzp6S7bQg6HYP7u8Qqe53tHR4-lZQLznw
Content-Type: application/json

###
PUT http://localhost:8080/database/<id>
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwODEyOTYiLCJuYW1lIjoibWFzdGVyIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE2Njk4MjAzNzB9.nQrtBB6suZ49uJsVGFg0w5uY0OcZn4iGubYsOsTqqYBR7xl5RSmmmgMm4Q6RM5wDup4eKmipFruc6ijSsdX6XozxoCRtrev0tuWsT1u5gL5IrkDPSeJv-jAckf1qQBGWBDftOwCbxDSvch2mRQ9CezLd1-1Rpn8DLVMxUA0soyGCAZ5mFsrSKqaqVEHq5Sp_nwrxjWoQWX9KH9TPjTpq2W2HwqZUGc48ejQO6C3h7Vx7mzZZwylN5_ckcU1eXkmIqIp0kCbU4qEUNOlPNxunA2109y_R4pZ9z3dWOYmEhYdIQ2HEnuba2Bzp6S7bQg6HYP7u8Qqe53tHR4-lZQLznw
Content-Type: application/json

{
  "logger": "<New Name>"
}
###
