GET http://localhost:30000/database
Authorization: Bearer <jwt>

###
GET http://localhost:30000/database/:id
Authorization: Bearer <jwt>

###
POST http://localhost:30000/database
Authorization: Bearer <jwt>

{
  "logger": "<new name>"
}
###
DELETE http://localhost:30000/database/:id
Authorization: Bearer <jwt>

###
PUT http://localhost:30000/database/:id
Authorization: Bearer <jwt>

{
  "logger": "Test Guy"
}
###
GET http://localhost:8080/database
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwODEyOTYiLCJuYW1lIjoibWFzdGVyIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE2Njk4MjM5NDYsImF1ZCI6ImhlbGxvIGF1ZGllbmNlIn0.XFIKhyiwrDQhbdM0hPC4DNqT8Q04tWaW2ZziJiP0vC-YRcSEnOsasBAyeaBay9Xinw5B1jIDRupxGef7mNl8LhfAdW8nuaHD9eNmEr1iRcF1cok6D_EPB98kZmdYwQP1kDLnaW0sz8jNkwdbXFM4jCCX8BRlaGJYctoMZqvYoeNwDkkKwMOboGVEU-Wbi82VqA4HH4o4AXqTKRzerK8CJYSEtdHvsFloQXVn6OuA9Lx_v85-Daop3NttxSCLYcnlZc0gO7gUV0q0DioOYM91Yp_wMBz8vEJI19cL1TQH6LvFzRbMcM2adPivi0QR9dqxrxim0vZK-HRMu23i0ew60w

###
GET http://localhost:8080/database/:id
Authorization: Bearer <jwt>

###
POST http://localhost:8080/database
Authorization: Bearer <jwt>

{
  "logger": "<new name>"
}
###
DELETE http://localhost:8080/database/:id
Authorization: Bearer <jwt>

###
PUT http://localhost:8080/database/:id
Authorization: Bearer <jwt>

{
  "logger": "<New Name>"
}
###
